#!/bin/bash
# 活动创建页面功能测试清单
# 使用方法: bash scripts/test-activity-create.sh

echo "🧪 活动创建页面功能测试清单"
echo "================================"
echo ""

echo "✅ 开发服务器已启动在 http://localhost:5174"
echo ""

echo "📋 手动测试步骤:"
echo ""

echo "1️⃣ 页面访问测试"
echo "   - 访问 http://localhost:5174/login"
echo "   - 登录后访问 http://localhost:5174/activity/create"
echo "   - 验证: 页面正常显示，所有表单字段可见"
echo ""

echo "2️⃣ 表单默认值测试"
echo "   - 检查报名开始时间 = 当前时间"
echo "   - 检查报名结束时间 = 明天"
echo "   - 检查活动开始时间 = 明天"
echo "   - 检查活动结束时间 = 下周"
echo "   - 检查最大参与人数 = 50"
echo "   - 检查公开活动 = true (开关打开)"
echo "   - 检查允许候补 = false (开关关闭)"
echo "   - 检查活动分类 = 商务会议"
echo ""

echo "3️⃣ 表单验证测试"
echo "   - 清空活动标题，点击提交 → 应显示 '请输入活动标题'"
echo "   - 输入1个字符的标题 → 应显示 '活动标题至少需要2个字符'"
echo "   - 清空活动描述 → 应显示 '请输入活动描述'"
echo "   - 输入少于10个字符的描述 → 应显示错误"
echo "   - 清空活动地点 → 应显示 '请输入活动地点'"
echo ""

echo "4️⃣ 时间验证测试"
echo "   - 设置报名结束时间早于开始时间 → 应显示错误"
echo "   - 设置活动结束时间早于开始时间 → 应显示错误"
echo "   - 设置报名结束时间晚于活动开始时间 → 应显示错误"
echo ""

echo "5️⃣ 图片上传测试"
echo "   - 点击上传封面图片"
echo "   - 选择一张图片"
echo "   - 验证: 显示上传进度"
echo "   - 验证: 上传成功后显示预览"
echo "   - 验证: 可以删除已上传的图片"
echo ""

echo "6️⃣ 表单提交测试"
echo "   - 填写所有必填字段"
echo "   - 点击 '创建活动' 按钮"
echo "   - 验证: 按钮显示 '创建中...'"
echo "   - 验证: 显示成功提示 Toast"
echo "   - 验证: 自动跳转到 /dashboard"
echo "   - 验证: Dashboard 显示新创建的活动"
echo ""

echo "7️⃣ 取消操作测试"
echo "   - 填写部分内容后点击 '取消'"
echo "   - 验证: 显示确认弹窗 '确定要放弃当前编辑的内容吗？'"
echo "   - 点击确认 → 跳转到 Dashboard"
echo "   - 不填写内容点击 '取消' → 直接跳转 Dashboard（无弹窗）"
echo ""

echo "8️⃣ 错误处理测试"
echo "   - 模拟网络错误（关闭 Mock 服务器）"
echo "   - 提交表单 → 应显示错误提示"
echo ""

echo "9️⃣ 移动端适配测试"
echo "   - 打开浏览器开发者工具"
echo "   - 切换到移动设备视图 (375px)"
echo "   - 验证: 所有元素正常显示"
echo "   - 验证: 按钮大小适合触摸（≥44px）"
echo "   - 验证: 表单可以正常滚动"
echo ""

echo "================================"
echo "测试完成后，请在待办事项中标记对应项目"
echo ""
